=== chan71177/chan71177.github.io/documents/XML & JSON/productschema.xsd
<?xml version="1.0"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
targetNamespace="http://southcentral.edu/ns/chandra/mkproduct"
xmlns:p="http://southcentral.edu/ns/chandra/mkproduct"
elementFormDefault="qualified">

<xs:element name="products">
    <xs:complexType>
        <xs:sequence>
            <xs:element name="product" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="type" type="xs:string"/>
                        <xs:element name="color" type="xs:string"/>
                    </xs:sequence>
                    <xs:attribute name="category" type="xs:string" use="required"/>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
</xs:element>

</xs:schema>

=== chan71177/chan71177.github.io/documents/XML & JSON/product.xml
<?xml version="1.0"?>
<?xml-stylesheet type="text/xsl" href="style.xsl"?>
<p:products xmlns:p="http://southcentral.edu/ns/chandra/mkproduct"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://southcentral.edu/ns/chandra/mkproduct productschema.xsd">
    <p:product category="makeup">
        <p:type>Lipstick</p:type>
        <p:color>Pretty-N-Pink</p:color>
    </p:product>
    <p:product category="makeup">
        <p:type>Eye Shadow</p:type>
        <p:color>Truffle</p:color>
    </p:product>
     <p:product category="makeup">
        <p:type>Foundation</p:type>
        <p:color>Beige 2.5</p:color>
    </p:product>
    <p:product category="skincare">
        <p:type>Moisturizer</p:type>
        <p:color>Normal/Dry</p:color>
    </p:product>
     <p:product category="tools">
        <p:type>Eyelash Curler</p:type>
        <p:color>Standard Size</p:color>
    </p:product>
</p:products>
